// GENERATED by scripts/gen-detachment-subfactions.mjs -- do not edit by hand.
// Source: BSData/wh40k-10e (10e). Regenerate with:
//   node scripts/gen-detachment-subfactions.mjs --edition 10e
//
// Absent = available to every sub-faction.
export const DETACHMENT_SUBFACTION: Record<string, string> = {
  "angelic inheritors": "Blood Angels",
  "black spear task force": "Deathwatch",
  "blade of ultramar": "Ultramarines",
  "champions of fenris": "Space Wolves",
  "companions of vehemence": "Black Templars",
  "company of hunters": "Dark Angels",
  "emperors shield": "Imperial Fists",
  "forgefathers seekers": "Salamanders",
  "godhammer assault force": "Black Templars",
  "hammer of avernii": "Iron Hands",
  "inner circle task force": "Dark Angels",
  "liberator assault group": "Blood Angels",
  "lions blade task force": "Dark Angels",
  "rage cursed onslaught": "Blood Angels",
  "reclamation force": "Ultramarines",
  "saga of the beastslayer": "Space Wolves",
  "saga of the bold": "Space Wolves",
  "saga of the great wolf": "Space Wolves",
  "saga of the hunter": "Space Wolves",
  "shadowmark talon": "Raven Guard",
  "spearpoint task force": "White Scars",
  "the angelic host": "Blood Angels",
  "the lost brethren": "Blood Angels",
  "unforgiven task force": "Dark Angels",
  "vindication task force": "Black Templars",
  "wrath of the rock": "Dark Angels",
  "wrathful procession": "Black Templars",
};

const norm = (s: string): string =>
  s
    .toLowerCase()
    .replace(/[‘’']/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

export const detachmentSubfaction = (name: string): string | null =>
  DETACHMENT_SUBFACTION[norm(name)] ?? null;
